apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fciv-net-frontend
  namespace: freeciv
  labels:
    app: fciv-net
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
