# LOCATION:freeciv-web/flyway.properties
flyway.user=matan
flyway.password=changeme
flyway.url=jdbc:mysql://#DB_HOST#:3306/freeciv_web?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
flyway.defaultSchema=freeciv_web
